# Generated by Django 6.1 on 2026-08-27 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elo', models.IntegerField()),
                ('wins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wincon', models.CharField(choices=[('FF', 'Forefeit'), ('CU', 'Culute'), ('SC', 'Science'), ('RG', 'Religion'), ('DP', 'Diplomacy'), ('DM', 'Domination')], max_length=2)),
                ('place1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player')),
                ('place2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player')),
                ('place3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player')),
                ('place4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player')),
                ('place5', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player')),
                ('place6', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player')),
                ('place7', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player')),
                ('place8', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player')),
            ],
        ),
    ]
