# Generated by Django 6.1 on 2026-08-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(db_default=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.IntegerField(db_default=0),
        ),
    ]
