# Generated by Django 6.1 on 2026-08-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0002_alter_player_elo_alter_player_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
