# Generated by Django 6.1 on 2026-08-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0003_alter_player_elo_alter_player_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='place3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='place4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='place5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='place6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='place7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='place8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='elo.player'),
        ),
    ]
