# Generated by Django 6.1 on 2026-08-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_alter_game_place3_alter_game_place4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='wincon',
            field=models.CharField(choices=[('FF', 'Forefeit'), ('CU', 'Culture'), ('SC', 'Science'), ('RG', 'Religion'), ('DP', 'Diplomacy'), ('DM', 'Domination')], max_length=2),
        ),
    ]
